@startuml

abstract class Command {
    Event[] execute()
}

class Event
class EventStore
class StatePersister
class Reactor

Command -down-> Event : produces
Event -down-> EventStore : flows into
EventStore -down-> StatePersister : persists events\ncollected from
EventStore -right> Reactor : reacts on events\ncollected from

@enduml